# Array Creation and Indexing in NumPy

In this notebook, we will learn how to create NumPy arrays and how to index and slice them. We will cover various methods for creating arrays and demonstrate how to access and manipulate their elements.

In [1]:
import numpy as np

# Creating a 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)

1D Array: [1 2 3 4 5]


In [2]:
# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:")
print(array_2d)

2D Array:
[[1 2 3]
 [4 5 6]]


In [3]:
# Creating an array of zeros
zeros_array = np.zeros((2, 3))
print("Array of Zeros:")
print(zeros_array)

Array of Zeros:
[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
# Creating an array of ones
ones_array = np.ones((3, 2))
print("Array of Ones:")
print(ones_array)

Array of Ones:
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [5]:
# Creating an array with a range of values
range_array = np.arange(0, 10, 2)
print("Array with Range of Values:", range_array)

Array with Range of Values: [0 2 4 6 8]


## Indexing and Slicing

Now that we have created some arrays, let's learn how to index and slice them.


In [6]:
# Indexing a 1D array
print("First element of 1D array:", array_1d[0])

# Slicing a 1D array
print("Sliced 1D array (elements 1 to 3):", array_1d[1:4])

First element of 1D array: 1
Sliced 1D array (elements 1 to 3): [2 3 4]


In [7]:
# Indexing a 2D array
print("Element at (1, 2) in 2D array:", array_2d[1, 2])

# Slicing a 2D array
print("Sliced 2D array (first row):", array_2d[0, :])

Element at (1, 2) in 2D array: 6
Sliced 2D array (first row): [1 2 3]


## Conclusion

In this notebook, we have learned how to create NumPy arrays using various methods and how to index and slice them. You can now practice these concepts further by creating your own arrays and experimenting with different indexing techniques.