# Broadcasting Concepts in NumPy

In this notebook, we will learn about broadcasting in NumPy. Broadcasting allows NumPy to perform operations on arrays of different shapes in a flexible way.

## Table of Contents
1. What is Broadcasting?
2. Broadcasting Rules
3. Examples of Broadcasting
4. Common Broadcasting Errors
5. Practical Applications
6. Conclusion

---

## 1. What is Broadcasting?

Broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. The smaller array is "broadcast" over the larger array so that they have compatible shapes.

---

## 2. Broadcasting Rules

- If arrays have a different number of dimensions, pad the shape of the smaller array with ones on its left side.
- Compare the shapes element-wise. Two dimensions are compatible when:
    - they are equal, or
    - one of them is 1

---

## 3. Examples of Broadcasting

In [1]:
import numpy as np

# Example 1: Adding a scalar to an array
a = np.array([1, 2, 3])
b = 10
result1 = a + b
print("Adding scalar:", result1)

# Example 2: Adding arrays of different shapes
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([10, 20, 30])
result2 = A + B
print("Adding 2D and 1D array:\n", result2)

# Example 3: Broadcasting with different dimensions
C = np.array([[1], [2], [3]])
D = np.array([4, 5, 6])
result3 = C + D
print("Broadcasting with column and row vectors:\n", result3)

Adding scalar: [11 12 13]
Adding 2D and 1D array:
 [[11 22 33]
 [14 25 36]]
Broadcasting with column and row vectors:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


---

## 4. Common Broadcasting Errors

If the shapes are not compatible, NumPy will raise a `ValueError`.

In [2]:
# Example of incompatible shapes
try:
    x = np.array([1, 2, 3])
    y = np.array([1, 2])
    z = x + y
except ValueError as e:
    print("Broadcasting error:", e)

Broadcasting error: operands could not be broadcast together with shapes (3,) (2,) 


---

## 5. Practical Applications

Broadcasting is useful for:
- Centering data (subtracting the mean)
- Normalizing arrays
- Applying operations across rows or columns

In [3]:
# Centering data
data = np.array([[1, 2, 3], [4, 5, 6]])
mean = data.mean(axis=0)
centered = data - mean
print("Centered data:\n", centered)

Centered data:
 [[-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]]


---

## 6. Conclusion

Broadcasting makes array operations flexible and efficient in NumPy. Understanding broadcasting rules helps avoid errors and write concise code.