# Vectorization Operations in NumPy

In this notebook, we will practice vectorization operations in NumPy. Vectorization allows us to perform operations on entire arrays without the need for explicit loops, leading to more efficient and concise code.

## Table of Contents
1. Introduction to Vectorization
2. Basic Vectorized Operations
3. Applying Functions to Arrays
4. Performance Comparison with Loops
5. Conclusion


In [1]:
# Importing NumPy
import numpy as np

# Introduction to Vectorization
print("Vectorization is a powerful feature of NumPy that allows for fast operations on arrays.")

Vectorization is a powerful feature of NumPy that allows for fast operations on arrays.


## 1. Basic Vectorized Operations

Let's start with some basic vectorized operations. We will create two NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [2]:
# Creating two NumPy arrays
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Element-wise operations
addition = a + b
subtraction = a - b
multiplication = a * b
division = a / b

addition, subtraction, multiplication, division

(array([ 6,  8, 10, 12]),
 array([-4, -4, -4, -4]),
 array([ 5, 12, 21, 32]),
 array([0.2       , 0.33333333, 0.42857143, 0.5       ]))

## 2. Applying Functions to Arrays

We can also apply mathematical functions to entire arrays. Let's see how to use NumPy's built-in functions.

In [3]:
# Applying functions
squared = np.square(a)
sqrt = np.sqrt(b)
exp = np.exp(a)

squared, sqrt, exp

(array([ 1,  4,  9, 16]),
 array([2.23606798, 2.44948974, 2.64575131, 2.82842712]),
 array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003]))

## 3. Performance Comparison with Loops

Let's compare the performance of vectorized operations with traditional loops.

In [4]:
# Performance comparison
import time

# Creating a large array
large_array = np.random.rand(1000000)

# Timing vectorized operation
start_time = time.time()
vectorized_sum = np.sum(large_array)
vectorized_time = time.time() - start_time

# Timing loop operation
start_time = time.time()
loop_sum = 0
for value in large_array:
    loop_sum += value
loop_time = time.time() - start_time

vectorized_time, loop_time

(0.001422882080078125, 0.19321537017822266)

## 4. Conclusion

In this notebook, we practiced vectorization operations in NumPy. We learned how to perform basic operations on arrays, apply functions efficiently, and compare the performance of vectorized operations with traditional loops.